version: '3'

services:
  database:
    networks:
        - database
    container_name: IPS3Database
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      # localhost port : container port
      - "1433:1433"
    restart: always
    volumes:
      - ./Data/mssql/data:/var/opt/mssql/data
      - ./Data/mssql/log:/var/opt/mssql/log
      - ./Data/mssql/secrets:/var/opt/mssql/secrets
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=m3ZS5g9YjPjct5am
  
  backendserver:
    networks:
      - database
      - backendserver
      - backendconnection
      - frontend
    container_name: ServerBackend
    ports:
      - "44337:44337"
    restart: always
    build: ./Server Backend/Server Backend 
    volumes:
      - ./Server Backend/Server Backend:/Server Backend/Server Backend
     
  backendconnection:
    networks:
      - database
      - backendserver
      - backendconnection
      - frontend
    container_name: ConnectionBackend
    depends_on:
      - database
    ports:
      - "44338:44338"
    restart: always
    build: ./Connection Backend/IPS-Backend 
    volumes:
      - ./Connection Backend/IPS-Backend:/Connection Backend/IPS-Backend
      
  frontend:
    networks:
      - backendserver
      - backendconnection
      - frontend
    depends_on:
      - backendserver
      - backendconnection
    container_name: IPS3Frontend
    build: ./Frontend
    volumes:
      - ./Frontend:/Frontend
    ports:
      - "19006:19006"
      - "19002:19002"
      - "19000:19000"
      - "19001:19001"

networks:
  backendserver:
    driver: bridge
  backendconnection:
    driver: bridge
  frontend:
    driver: bridge
  database:
    driver: bridge