name: Test

on: [push]

  
jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
            node-version: 16
      
      - name: Install modules
        run: npm install

      - name: Run Frontend tests
        working-directory: ./Frontend
        run: npm test -u