name: Test

on: [push]

  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Frontend tests
        working-directory: ./Frontend
        run: npm test -- -u