name: TestServerBack

on: [push]


jobs:
  TestServerBack:
    runs-on: ubuntu-latest

    defaults:
        run:
            working-directory: ./Server Backend

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 5.0 
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
