name: Test

on: [push]

  
jobs:
  Tests:
    runs-on: ubuntu-latest
    
    defaults:
        run:
            working-directory: ./Frontend

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
            node-version: 16
            cache: npm
      
      - name: Install modules
        run: npm install

      - name: Run Frontend tests

        run: npm test -- -u