name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Setup Jest
      run: npm install -g jest
      
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.3